apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: urlshortener-api
    app: urlshortener-api
  name: urlshortener-api-metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      port: 9110
      protocol: TCP
      targetPort: 9110
  selector:
    control-plane: urlshortener-api
