apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: urlshortener-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: urlshortener-api-role
subjects:
  - kind: ServiceAccount
    name: urlshortener-api
    namespace: system
