# permissions for end users to view shortlinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shortlink-viewer-role
rules:
- apiGroups:
  - urlshortener-api.cedi.dev
  resources:
  - shortlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - urlshortener-api.cedi.dev
  resources:
  - shortlinks/status
  verbs:
  - get
