# permissions for end users to edit shortlinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shortlink-editor-role
rules:
- apiGroups:
  - urlshortener-api.cedi.dev
  resources:
  - shortlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener-api.cedi.dev
  resources:
  - shortlinks/status
  verbs:
  - get
